### ISSUE TITLE
Option to choose database-adapter

### ISSUE THREAD

**Issue by jcpst** [feathersjs/generator-feathers#103]
Is there interest in in adding a database-adapter choice in the app generator? Say, if someone wanted to generate apps and services that used knex?

**Comment by ekryski** [comment]
Hey @jcpst! I think eventually, yes. Support for choosing a database and then optionally choosing a driver/adapter for it. Definitely open to PRs if you wanted to put something together! :smile:

Initially we decided that we would be opinionated with the generator and map databases to what we think are the best drivers for that db. This makes it easier for people that are not only new to Feathers but also new to Node in general. Right now the only way to use knex through the generator is select the "use my own db" option and implement it yourself.

I see this fitting in with #33. The UX might need to be worked out so that noobs aren't overwhelmed with options but I think we can probably make it work somehow.

**Comment by sylvainlap** [comment]
+1

Currently, the CLI does not allow to choose Knex.
