### ISSUE TITLE
Can we move server to src

### ISSUE THREAD

**Issue by daffl** [feathersjs/generator-feathers#11]
A little nit-picky and it may a very personal preference but I always keep my server code in a `src/` folder. Especially if we decide to push for more universal applications it will become very mixed up with client code anyway.

**Comment by marshallswain** [comment]
`src` is definitely more consistent.  I only like to use `server` because it's easy to distinguish between my server and client projects, which I like to keep separate, but I guess you're right.  It probably won't matter moving forward.

**Comment by slajax** [comment]
Are we suggesting `src/server`?

In my projects, I often do something like:
```
- src/
  - server/
    - index.js
    - app.js
  - module1/
    - index.js
  - module2/
    - index.js
```

That way if you add `src` or `lib`, depending on if you are compiling or not, to your `NODE_PATH` you can reference server as a first class module, which can be nice because you don't have to worry about paths as long as your env is set right.

Just a suggestion.
