### ISSUE TITLE
Feature: choose between ESLint + AirBnB and jshint?

### ISSUE THREAD

**Issue by harangue** [feathersjs/generator-feathers#112]
[ESlint and AirBnB's config for it](https://www.npmjs.com/package/eslint-config-airbnb) is an extremely popular choice for linting in the JS community. It's not difficult to add to an existing generator-feathers project, but it throws enough errors to be a nuisance to fix.

A generator should probably be unopinionated, and AirBnB's is anything but. At the same time, I think there's a possibility of adding it as an option in the generator without it getting in the way.

I did a clean generate with mongoose services / modals and here are some of the rules being violated.
- **space-in-parens** (There shouldn't be spaces in parenthesis) _e.g. app.js:24_
- **eol-last** (There should be a new line at the end of a file) _e.g. index.js:9_
- **func-names** (Name all function expressions) _e.g. index.js:6_
- **space-before-function-parent** (Space before function parenthesis) _e.g. index.js:6_
- **comma-dangle** (Trail commas) _e.g. user/index.js:14_
- **no-trailing-spaces** (No blank characters at the end of a line) _e.g. user/user-model.js:14_
- **quote-props** (Unnecessarily quoted properties) _e.g. user/user-model.js:15_

There are more that I didn't feel like looking through. :P Overall they're pretty minor grievances, but could change the look of the code significantly.

Regardless, I think this would be a great option for the feathers-generator, or just make it the default style that the generator generates in.

**Comment by ekryski** [comment]
> A generator should probably be unopinionated

Actually, our thought is that the generator **should** be opinionated. The modules themselves should be as flexible as possible.

Not to sound negative, but the intention of the generator is to be opinionated and if you like the style of code it generates than it can make your life easier. If it's not doing that for you because you like your code structured a certain way then you are free to change the generated code or not use the generator. It is easy to assemble all the pieces of a Feathers app and structure it manually as well.

The problem with implementing this is that, beyond all the other combinations of options, if we have to now generate different code style depending on whether someone wants to use jshint or eslint, It will be a maintainability nightmare. The generator is already our most fragile piece.

So my vote is respectfully that I don't think it's worth the effort. However, if a PR is sent that doesn't change the code structure significantly then I would be open to merging it.

**Comment by harangue** [comment]
@ekryski When I said unopinionated I didn't mean that the generator doesn't make any choices for the user. My thought in general is that there's opinionated and then there's *opinionated*. So there are things like the directory structure of a Feathers project, where, while there are many possible valid combinations, the way you all have it set up maximizes maintainability and organization. You all don't offer choices in the generator for these, they just are.

However I dispute the claim that choosing a code style is fundamentally different from picking, say, Primus over Socket.io. It's not a clear-cut choice - there are perfectly valid reasons to want to rely on either library and ultimately it depends on the developer. Code style is just another one of those choices: the semicolon vs. no semicolon debate, the brace position debate, and the class-style syntax debate are all choices a developer makes that are very much capital-O *Opinions*.

Whether or not you think it would hurt the maintainability of the repo is definitely a concern for me as well (and one @daffl and I were discussing in Slack earlier), but I don't think it invalidates the idea of adding code-style options to a generator. It's not like doing so is outside the purpose of a generator - it's just supposed to write boilerplate code that you can use.

Since as far as I can tell the AirBnB config rules aren't in conflict with the JSHint stuff you all have set up, there's technically nothing preventing me from going in a making it comply. The issue is whether or not there would be motivation in maintaining it in that state in the future, which it sounds to me like there's probably not.

Still, I think a generator that doesn't try to accommodate a style that's as popular as AirBnB's is in the JS community is going to miss out on a lot of goodwill / adoption in the community. Just my two cents.

**Comment by ekryski** [comment]
@harangue Like I said, if it's a pretty easy change so that the same code works for both jshint and eslint then 👍  for sure. However, if we have to maintain two separate code paths **plus** all the possible combinations that the generator currently provides then my opinion is that we should stick with one linting style or another, at least for now...

This is my opinion and would love to hear what the rest of the @feathersjs/core-team thinks, however if someone wants to step up and maintain it at the rate it has been currently then by all means. I simply am not able to and I already feel that the generator is too fragile. We've sort of been holding off adding more stuff to it in general until we get a better testing solution in place.

**Comment by harangue** [comment]
@ekryski Well here's something fun I just found... ESLint has a `--fix` flag that automatically fixes a good number of the discrepancies between your code and config file. Looking through it won't be able to fix all of them (named anonymous functions, for instance) and it seems it isn't super widely implemented, but I'm wondering if there would be a way to generate output that's in compliance with a supplied ruleset. *That* would be cool. I'll keep digging though.

**Comment by daffl** [comment]
We just merged #159 and released a v1.0.0-pre.1 which includes ESLint by default so `--fix` can be used. Given how much work it is to maintain the generator in general, we probably won't add any other options. For different code styles anybody is welcome to fork this repository and modify it to their own requirements.
