### ISSUE TITLE
Facebook/Google/Github Profile

### ISSUE THREAD

**Issue by dschnare** [feathersjs/generator-feathers#225]
Authentication generator configures OAuth2 providers really well, but nothing is actually being done with the profile. It would be great to have the profile saved on the `users.model.js` model. I had to stumble my way through several experiments before I figured out how to do this properly. At least, pull out the primary email from the profile and have that saved to the user model.

**Comment by daffl** [comment]
This was intentional because the profile can not easily be saved into SQL databases (you'd need a full schema for it).

The documentation does have a [section about customizing the OAuth2 verifier](https://docs.feathersjs.com/api/authentication/oauth2.html#verifier) which is how you can customize how the user is being saved.

**Comment by dschnare** [comment]
Thanks for the link, I hadn't realized that the verifier was what needed to be customized to change how users were stored.

**Comment by daffl** [comment]
I was wondering if anything in the docs needs to be updated but it does say

> This is the verification class that handles the OAuth2 verification by looking up the entity (normally a user) on a given service and either creates or updates the entity and returns them.

So I'm not sure what else could be added there.

**Comment by dschnare** [comment]
Nothing lol. That's just my selective vision missing the docs ;) Trying to skim and learn don't mix well. Thanks for looking.
