### ISSUE TITLE
App generator: Ask for public folder and possibly colocated tests

### ISSUE THREAD

**Issue by dschnare** [feathersjs/generator-feathers#226]
As part of the app generator it would nice/complete if users were asked where to put the `public/` folder. For example, I could put my source in `web/src` and my static assets in `web/public`.

Also, it would be nice (wishful thinking) if I were asked where tests should be located. The default could be `test`, but another option would be `(colocated)`. Colocated would mean that tests would be located next to the file/module they were testing.

**Comment by daffl** [comment]
Thank you for the suggestion. Our goal with the generator is to pick sane defaults and keep the number of prompts as low as possible, especially when it is not relevant to other generators. Every new prompt will have to be implemented, tested, documented and released and also requires all tutorials  that are showing and/or explaining the prompts (including screenshots) to be updated.

Both changes you are suggesting can be made by editing a JSON file. The public folder can be changed by renaming it and updating the configuration value in `config/default.json` to the new path. Support for customizing the test folder has been added in #218. Tests will be generated into the folder specified in`lib.test` in the `package.json`.

**Comment by dschnare** [comment]
Good points, but now you guys are pigeonholed into what you got. Is there anyway to automate some of the process in updating tutorials/guides/screenshots? I suppose there would only actually be a few steps that have the potential for automation. Anyway, thanks for the feedback @daffl.

**Comment by daffl** [comment]
Definitely possible but also probably a lot of work (I know of an open source project where it took a developer a month full time to implement something similar).

What I'm trying to say is that we'd like to avoid adding prompts for style choices and anything that only requires changing one or two lines of code (especially since outside of JSON files, modifying existing code programmatically is quite complicated and brittle).

I'm definitely going to write up a guide on how to fork and customize the generator for your own needs though and pull requests against the generator are always going to be considered of course.

**Comment by dschnare** [comment]
Thanks for the insight. I figured forking would be the best thing for us. We'd be able to make modifications and be able to pull in changes from upstream and send pull requests for any issues we resolve.

**Comment by daffl** [comment]
Sounds good. Pull requests are always welcome 😄

**Comment by kfern** [comment]
@daffl Any progress in the guide on how to fork and customize the generator?

**Comment by daffl** [comment]
You `npm install -g yo`, fork the generator, clone your fork, then `npm link` in the cloned folder and run `yo`.
