### ISSUE TITLE
Don't overwrite customized Mongoose schemas

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/generator-feathers#249]
If you generate a service and customize users.model.js with a custom schema, then add auth, it reportedly overwrites the schema file.  We need to make sure it at least warns before-hand.

**Comment by daffl** [comment]
I wonder if this is because of https://github.com/feathersjs/generator-feathers/blob/master/generators/service/index.js#L150 which is mainly for not asking to overwrite the index files when adding the import. Can you maybe try resetting it back to false after writing those specific files and see if that will prompt you to overwrite?
