### ISSUE TITLE
Generator ignores service name (or incorrect expectations)

### ISSUE THREAD

**Issue by chris-garrett** [feathersjs/generator-feathers#291]
When creating a new service and providing a pascal case name, that name is ignored for:

- directory names
- file names
- table definition: 
```
const userIdentity = sequelizeClient.define('user-identity', {
```
- service options. 
```
  const options = {
    name: 'user-identity',
    Model,
    paginate
  };
```

Steps:
```
bash-4.3$ feathers --version
2.3.4
bash-4.3$ feathers g service
? What kind of service is it? Sequelize
? What is the name of the service? UserIdentity
? Which path should the service be registered on? /UserIdentity
? Does the service require authentication? Yes
? Which database are you connecting to? PostgreSQL
   create src/services/user-identity/user-identity.service.js
    force src/services/index.js
   create src/models/user-identity.model.js
   create src/services/user-identity/user-identity.hooks.js
   create src/services/user-identity/user-identity.filters.js
   create test/services/user-identity.test.js
```

**Comment by daffl** [comment]
Since you can name a service anything, any name will be turned into a safe kebab-cased name since that seems to be what most databases support (although this might have to be changed for the table name in Sequelize as it was in Knex already via https://github.com/feathersjs/generator-feathers/pull/289).

You can always adjust the name manually afterwards.
