### ISSUE TITLE
use requireDir for load global hooks?

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/generator-feathers#42]
Maybe it make sense to use [requireDir](https://github.com/aseemk/requireDir) for load all hooks from `/src/hooks` folder?

It can looks like:
`/src/services/user/hooks/index.js`
```javascript
var requireDir = require('require-dir');
const globalHooks = requireDir('../../../hooks', {recurse: true});
import { hooks as auth } from 'feathers-authentication';

let before = {
  all: [globalHooks.myHook()],
  find: [],
  get: [],
  create: [],
  update: [],
  patch: [],
  remove: []
};

let after = {
  all: [],
  find: [],
  get: [],
  create: [],
  update: [],
  patch: [],
  remove: []
};

export default { before, after };
```

Instead of:
```javascript
import globalHooks from '../../../hooks';
```

<img width="230" alt="2016-02-20 15 12 20" src="https://cloud.githubusercontent.com/assets/557190/13196635/6480acb6-d7e4-11e5-8d17-4160b41d94ce.png">

This will enable us to abandon the creation of an index file in `/src/hooks`.

**Comment by daffl** [comment]
I've been playing with that idea, too but in my experience, doing this caused some really hard to debug errors if someone accidentally puts a JS file that doesn't look the way you'd expect into the folder.

Now that we are using AST transformations (https://github.com/feathersjs/generator-feathers/pull/48) instead of regular expressions to add the imports things are hopefully much less brittle and it is clear what is being imported without any additional dependency.
