### ISSUE TITLE
Expand CLI prompts

### ISSUE THREAD

**Issue by MauriceArikoglu** [feathersjs/generator-feathers#581]
@daffl 

I offer to fix #519 myself and also propose to add some further options to the CLI, including:
- asking the user whether they need a `.gitignore`
    - and if yes, whether they want to edit the default `.gitignore`
- asking the user whether they need a `.editorconfig`
    - and if yes, whether they want to edit the default `.editorconfig`

For fixing #519 I need to understand the requirements better, please correct me if this CLI flow needs optimizing:
- asking the user whether they need a hostname
    - and if yes, allow the user to set the hostname

If there are further suggestions, feel free to reach out, I might be able to include them as well.

**Comment by daffl** [comment]
First of all, thank you for your contributions @MauriceArikoglu! The merged PRs have now been published.

Before we dive more into customizing this generator, I created an issue with the plans for a new CLI in https://github.com/feathersjs/cli/issues/253. It would be great to get some feedback and possibly help on this since I believe it will allow for a CLI that is more flexible, easier to maintain and easier to customize.

**Comment by MauriceArikoglu** [comment]
@daffl great. I quickly read over it, sounds reasonable. It's late already where I am. I'll get back to you tomorrow, after reading it one more time!

- Maurice

**Comment by daffl** [comment]
The new CLI is now available in [the v5 prerelease](https://dove.feathersjs.com/guides/migrating.html#testing-the-prerelease). It addresses many of those issues and is much more flexible and faster (including faster installation with drastically reduced dependencies). Further development is happening in https://github.com/feathersjs/feathers
