### ISSUE TITLE
Add webpack dev and prod setup

### ISSUE THREAD

**Issue by daniel79** [feathersjs/generator-feathers#93]
Love feathers but found hard to setup webpack for both dev and prod. Would be nice to have it.

**Comment by daffl** [comment]
This is probably related to #73. We're looking to tackle some of the frontend stuff in the near future. It does sound more like a Webpack than a Feathers problem though, unless there are things specific to Feathers that are causing issues.

**Comment by daffl** [comment]
I created a follow-up issue in https://github.com/feathersjs/feathers-docs/issues/169 to include a Webpack setup guide. I am going to close this issue however since we are not planning to include this in the generator until we decided if and what to support for the frontend. There are also some great [starters](https://github.com/randomnerd/feathers-react-pg) that include a Webpack setup out there already.
